apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopscloud
  template:
    metadata:
      labels:
        app: devopscloud
    spec:
      serviceAccountName: jenkins
      containers:
        - name: devopscloud
          image: 11711911/devopscloud
