apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      serviceAccountName: jenkins
      containers:
        - name: devops
          image: 11711911/devops
